### ISSUE TITLE
Import loop breaking

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/PACMAN#257] opened 2019-09-05 09:35 UTC
#256 (and its associated PRs downstream) has a few places where an import loop needed to be broken. The technique I used was to identify a class that was only ever actually needed at runtime (usually easy) and to move the lookup of that class to actually occur when it was first needed. For example, in `application_edge.py`:
```python
_MachineEdge = None

def _machine_edge_class():
    global _MachineEdge  # pylint: disable=global-statement
    if _MachineEdge is None:
        from pacman.model.graphs.machine import MachineEdge
        _MachineEdge = MachineEdge
    return _MachineEdge
```

If you see that pattern (used because application edges can manufacture machine edges), that's what is happening. This ugly pattern was only put in because _otherwise things don't work._

We ought to look if there's a better way. There may be…

**Comment by dkfellows** [comment] 2019-09-05 09:42
The only fundamental thing wrong with this code is that it's a bit ugly and tricky.

**Comment by rowleya** [comment] 2019-09-05 09:46
I believe that the rule for import loop breaking is to not allow co-dependent packages.  Note this is only an issue if we use the __init__.py file in the way we currently are.  The issue is that import from one package to another then imports everything in that package as it always calls __init__.py even if you are referencing a class from within the package directly.  So the loop is usually due to looping package dependencies.

**Comment by Christian-B** [comment] 2019-09-05 10:06
I discussed this @donal and suggested that the current work of removing the graph mapper goes ahead even if the there is some uglier import loop breaking being done.

Once that work is finished and merged in we can then look calmly at what is needed where and see if a less ugly way can be found without making the structure crazy.

**Comment by alan-stokes** [comment] 2019-09-05 10:07
id say thats lazy. get it fixed properly then we can assess it as a whole. theres no rush in removing the gm.

**Comment by alan-stokes** [comment] 2020-06-29 08:28
fixed. this import loop is no longer in existence. closing issue.

**Closed by alan-stokes** 2020-06-29 08:28 UTC
Labels: bug
