### ISSUE TITLE
Partitioner not consitant

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/PACMAN#201] opened 2019-03-12 08:58 UTC
Even using the exact same physical board (Spin03)  and the eaxact same script and config file the partitioner sometimes swaps the order of placement.

Sure I know that this should not matter but had we not intended they be constant for debuging and testing.

Example:
        sim.setup(timestep=1.0)
        sim.set_number_of_neurons_per_core(sim.IF_curr_exp, 100)

        input = sim.Population(1, sim.SpikeSourceArray(spike_times=[0]),
                               label="input")
        pop_1 = sim.Population(200, sim.IF_curr_exp(), label="pop_1")
        sim.Projection(input, pop_1, sim.AllToAllConnector(),
                       synapse_type=sim.StaticSynapse(weight=5, delay=18))
        sim.run(500)

option A:
 Processor 3: Vertex: 'input', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: SpikeSourceArrayVertex

  Processor 4: Vertex: 'input_delayed', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: DelayExtensionVertex

Option B:
 Processor 3: Vertex: 'input_delayed', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: DelayExtensionVertex

  Processor 4: Vertex: 'input', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: SpikeSourceArrayVertex

**Comment by dkfellows** [comment] 2019-07-26 07:31
Is this an issue in Python 3.7?

**Comment by alan-stokes** [comment] 2019-09-26 15:03
could it be that the sort of the DefaultOrderedDict is not deterministic if say the len of 2 constraints set is the same? as i cant see anywhere else where this could exhibit itself from

**Comment by Christian-B** [comment] 2020-06-04 06:59
Is this fixed or coul dit be part of the Vogels inconstency issue?

**Comment by alan-stokes** [comment] 2020-06-04 12:42
in all honestly. i have not witnessed it doing so. but then. i wasn't exactly fully looking at the placements every time. i checked over 3 runs and left it..... if its a intermittent issue. then i wouldn't have picked it up. 

question boils down to why the partitioner/placer could ever be in a different order..... everything in that level looks like ordereddicts or ordered sets. I dont know if we ever fixed whatever the issue is. i can have a gander shortly

**Comment by rowleya** [comment] 2020-06-05 07:02
Given when this was submitted, it may simply be that it has been fixed since this was submitted.  Note that this reports inconsistency in placement which could come from the building of the machine graph or from the placement algorithm itself.  I could see why this could happen in the one-to-one placer which builds up groups; I think this has been improved recently but it is worth a look just in case that is the cause of the inconsistency.

**Comment by alan-stokes** [comment] 2020-06-16 10:20
having reran the vogals many times now in a effort to determinism the plastic side, i can tell ya that the placement never changed. so closing issue on the theory if this ever comes back, you can reopen it.

**Closed by alan-stokes** 2020-06-16 10:20 UTC
Labels: bug, minor
