### ISSUE TITLE
Fixed rout router bug

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/PACMAN#141] opened 2017-12-07 13:15 UTC
Test: https://github.com/SpiNNakerManchester/sPyNNaker8/blob/master/p8_integration_tests
/test_param_vertex_retrieval_from_board_after_1_run/test_synfire_20n_20pc_delays_delay_extensions_all_recording.py
test_with_constarint

../scripts/synfire_run.py:277: in do_run
    p.run(run_times[-1])
../../spynnaker7/pyNN/__init__.py:161: in run
    globals_variables.get_simulator().run(run_time)
../../../sPyNNaker/spynnaker/pyNN/abstract_spinnaker_common.py:315: in run
    AbstractSpinnakerBase._run(self, run_time)
../../../SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py:904: in _run
    self._do_mapping(run_time, n_machine_time_steps, total_run_time)
../../../SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py:1650: in _do_mapping
    optional_algorithms)
../../../SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py:1157: in _run_algorithms
    executor.execute_mapping()
../../../PACMAN/pacman/executor/pacman_algorithm_executor.py:597: in execute_mapping
    self._execute_mapping()
../../../PACMAN/pacman/executor/pacman_algorithm_executor.py:613: in _execute_mapping
    results = algorithm.call(self._internal_type_mapping)
../../../PACMAN/pacman/executor/algorithm_classes/abstract_python_algorithm.py:47: in call
    results = self.call_python(method_inputs)
../../../PACMAN/pacman/executor/algorithm_classes/python_class_algorithm.py:59: in call_python
    return method(**inputs)
../../../PACMAN/pacman/operations/fixed_route_router/fixed_route_router.py:105: in __call__
    destination_class, machine)
../../../PACMAN/pacman/operations/fixed_route_router/fixed_route_router.py:143: in _do_dynamic_routing
    p=destination_processor, vertex=vertex_dest))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = (1, 1, 4)(0, 0, 4)
placement = Placement(vertex=MachineVertex(label=None, constraints=set([]), x=0, y=0, p=4)

    def add_placement(self, placement):
        """ Add a placement
    
            :param placement: The placement to add
            :type placement:\
                :py:class:`pacman.model.placements.placement.Placement`
            :raise PacmanAlreadyPlacedError:\
                If there is any vertex with more than one placement.
            :raise PacmanProcessorAlreadyOccupiedError:\
                If two placements are made to the same processor.
            """
        placement_id = (placement.x, placement.y, placement.p)
        if placement_id in self._placements:
>           raise PacmanProcessorAlreadyOccupiedError(placement_id)
E           PacmanProcessorAlreadyOccupiedError: (0, 0, 4)

But the constraint is only x=0, y=0

**Comment by alan-stokes** [comment] 2017-12-07 13:30
i cant reproduce this error. i do produce a error about int having no len () in sypnaker plotting.

**Comment by alan-stokes** [comment] 2017-12-07 13:30
2017-12-07 13:29:01 WARNING: This call is not standard pynn and therefore will not be compatible between simulators. Nor do we guarantee that this function will exist in future releases.
Getting gsyn_excitatory for pop_1
|0%                          50%                         100%|
 ============================================================
2017-12-07 13:29:01 INFO: Turning off machine
Traceback (most recent call last):
  File "/media/alan/DATA/spinnaker_software/sPyNNaker8/p8_integration_tests/test_param_vertex_retrieval_from_board_after_1_run/test_synfire_20n_20pc_delays_delay_extensions_all_recording.py", line 121, in <module>
    annotations="generated by {}".format(__file__))
  File "/home/alan/pynn0.8/local/lib/python2.7/site-packages/pyNN/utility/plotting.py", line 201, in __init__
    panel.plot(plt.subplot(gs[i, 0]))
  File "/media/alan/DATA/spinnaker_software/sPyNNaker8/spynnaker8/spynnaker_plotting.py", line 301, in plot
    plot_segment(axes, segment, label=label, **properties)
  File "/media/alan/DATA/spinnaker_software/sPyNNaker8/spynnaker8/spynnaker_plotting.py", line 205, in plot_segment
    **options)
  File "/media/alan/DATA/spinnaker_software/sPyNNaker8/spynnaker8/spynnaker_plotting.py", line 161, in heat_plot_neo
    xs = range(len(n_neurons))
TypeError: object of type 'int' has no len()

**Comment by Christian-B** [comment] 2017-12-08 08:15
did get to the plotting error once.

But now on a windows machine spin3 board lastest build so including the fix I still get the above error.

Commenting out the constraint and I get the spinn_front_end_common.utilities.exceptions.SpinnFrontEndException: Failed to hear from the machine during 21 attempts. Please try removing firewalls

And NO it is NOT firewalls as other scripts run fine

**Comment by Christian-B** [comment] 2017-12-08 08:27
len MESS fixed in https://github.com/SpiNNakerManchester/sPyNNaker8/pull/93

**Comment by Christian-B** [comment] 2017-12-14 10:14
could not replicate with a spin three board.

However does occur with spalloc both on the normal port and the test port

**Comment by Christian-B** [comment] 2017-12-14 10:22
This bug still occurs with fix-2  and using SPALLOC

**Comment by alan-stokes** [comment] 2017-12-14 10:35
cant be reproduced here. But i think im missing a test. the tests i have in that intergration test do not include a test_with_constraint. it only includes:
test_all_constarint
test_all_no_constarint

I also note that the __main__ doesnt call the same functions, and i can only test via the main. so the test needs to be usable before i can try to diagnoise it

**Comment by alan-stokes** [comment] 2017-12-14 11:44
fixed in fix2 branch

**Comment by alan-stokes** [comment] 2017-12-14 11:50
fix code (if you want to cherry pick) is lcoated here:
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/blob/fix_2/spinn_front_end_common/interface/interface_functions/insert_extra_monitor_vertices_to_graphs.py

**Comment by alan-stokes** [comment] 2017-12-20 17:19
fixed. reopen if otherwise

**Closed by alan-stokes** 2017-12-20 17:19 UTC
Labels: bug
